#!/bin/sh

rm -rf ~/.vim \
       ~/.vimrc \
       ~/.zshrc \
       ~/.zprofile \
       ~/.zpreztorc \
       ~/.zprezto/modules/prompt/functions/prompt_water_setup \
       ~/.gitconfig \
       ~/.gitignore \
       ~/.config/mpv/mpv.conf \
       ~/.yabairc
       ~/.skhdrc

# zsh

ln -s ./zshrc ~/.zshrc
ln -s ./zprofile ~/.zprofile

# vim

ln -s ./vim ~/.vim
ln -s ./vim/vimrc ~/.vimrc

# git

ln -s ./git/gitconfig ~/.gitconfig
ln -s ./git/gitignore ~/.gitignore

# prezto

ln -s ./prezto/zpreztorc ~/.zpreztorc
ln -s ./prezto/prompt_water_setup ~/.zprezto/modules/prompt/functions/prompt_water_setup

# mpv

ln -s ./mpv.conf ~/.config/mpv/mpv.conf

# yabai

ln -s ./yabairc ~/.yabairc
ln -s ./skhdrc ~/.skhdrc