#!/bin/sh

rm -rf ~/.vim \
       ~/.vimrc \
       ~/.zshrc \
       ~/.zprofile \
       ~/.zpreztorc \
       ~/.gitconfig

# zsh

ln -s ~/dotfiles/zsh/zshrc ~/.zshrc

# vim

ln -s ~/dotfiles/vim ~/.vim
ln -s ~/dotfiles/vim/vimrc ~/.vimrc

# git

ln -s ~/dotfiles/gitconfig ~/.gitconfig

# prezto

ln -s ~/dotfiles/zsh/zprofile ~/.zprofile
ln -s ~/dotfiles/zsh/zpreztorc ~/.zpreztorc
ln -s ~/dotfiles/zsh/prompt_water_setup ~/.zprezto/modules/prompt/functions/prompt_water_setup
